# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(64)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -3, 1011, 51))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(-1)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #474242;\n"
"    color: #cfc8c8;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    border-radius: 40%;\n"
"    color: #cfc8c8;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size: 14px;\n"
"    color: #cfc8c8;\n"
"    background-color: #474242;\n"
"    border: 1px solid #cfc8c8;\n"
"    border-radius: 13%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #474242;\n"
"    background-color: #cfc8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #cfc8c8;\n"
"    background-color: #5c5656;\n"
"    border-color: #5c5656;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #474242;\n"
"    background-color: #474242;\n"
"    border-color: #474242;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 13px;\n"
"    background-color: #cfc8c8;\n"
"    color: #474242;\n"
"    border-radius: 10%;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #cfc8c8;\n"
"}\n"
"\n"
"QCheckBox:indicator:unchecked {\n"
"    background-color: #5c5656;\n"
"}\n"
"\n"
"QCheckBox:indicator:checked {\n"
"    background-color: #cfc8c8;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(600, 12, 301, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timer = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(-1)
        self.timer.setFont(font)
        self.timer.setAlignment(QtCore.Qt.AlignCenter)
        self.timer.setObjectName("timer")
        self.horizontalLayout.addWidget(self.timer)
        self.spm = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(-1)
        self.spm.setFont(font)
        self.spm.setAlignment(QtCore.Qt.AlignCenter)
        self.spm.setObjectName("spm")
        self.horizontalLayout.addWidget(self.spm)
        self.acc = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(-1)
        self.acc.setFont(font)
        self.acc.setAlignment(QtCore.Qt.AlignCenter)
        self.acc.setObjectName("acc")
        self.horizontalLayout.addWidget(self.acc)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(5, 11, 431, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(10, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.new_button.setMinimumSize(QtCore.QSize(94, 26))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.new_button.setFont(font)
        self.new_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout_2.addWidget(self.new_button)
        self.leave_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.leave_button.setMinimumSize(QtCore.QSize(94, 26))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.leave_button.setFont(font)
        self.leave_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.leave_button.setObjectName("leave_button")
        self.horizontalLayout_2.addWidget(self.leave_button)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.min_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.min_line.setMinimumSize(QtCore.QSize(100, 20))
        self.min_line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.min_line.setFont(font)
        self.min_line.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.min_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line.setMaxLength(4)
        self.min_line.setFrame(True)
        self.min_line.setAlignment(QtCore.Qt.AlignCenter)
        self.min_line.setPlaceholderText("text length")
        self.min_line.setClearButtonEnabled(False)
        self.min_line.setObjectName("min_line")
        self.horizontalLayout_2.addWidget(self.min_line)
        self.lang_list = QtWidgets.QComboBox(self.frame)
        self.lang_list.setGeometry(QtCore.QRect(907, 17, 81, 22))
        self.lang_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lang_list.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lang_list.setStyleSheet("QComboBox {\n"
"    font-size: 12px;\n"
"    color: #cfc8c8;\n"
"    background-color: #474242;\n"
"    padding: 2px;\n"
"}")
        self.lang_list.setMaxCount(12)
        self.lang_list.setIconSize(QtCore.QSize(16, 16))
        self.lang_list.setFrame(False)
        self.lang_list.setModelColumn(0)
        self.lang_list.setObjectName("lang_list")
        self.lang_list.addItem("")
        self.lang_list.addItem("")
        self.lang_list.addItem("")
        self.check_lowercase = QtWidgets.QCheckBox(self.frame)
        self.check_lowercase.setGeometry(QtCore.QRect(436, 11, 131, 30))
        self.check_lowercase.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(7)
        self.check_lowercase.setFont(font)
        self.check_lowercase.setFocusPolicy(QtCore.Qt.NoFocus)
        self.check_lowercase.setObjectName("check_lowercase")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.lang_list.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Heh Typer"))
        self.timer.setText(_translate("MainWindow", "s"))
        self.spm.setText(_translate("MainWindow", "s/m"))
        self.acc.setText(_translate("MainWindow", "%"))
        self.new_button.setText(_translate("MainWindow", "New Round"))
        self.leave_button.setText(_translate("MainWindow", "Leave Round"))
        self.lang_list.setCurrentText(_translate("MainWindow", "english"))
        self.lang_list.setPlaceholderText(_translate("MainWindow", "language"))
        self.lang_list.setItemText(0, _translate("MainWindow", "english"))
        self.lang_list.setItemText(1, _translate("MainWindow", "russian"))
        self.lang_list.setItemText(2, _translate("MainWindow", "ukrainian"))
        self.check_lowercase.setText(_translate("MainWindow", "lowercase only"))
